# Вычислительная математика. Домашняя лабораторная работа №2.
### Выполнил: Хайдари Фарид, группа Б01-909.

## Подготовка среды

In [48]:
# Включаем все необходимые библиотеки
import numpy as np

In [63]:
# Задаем глобальные константы
SIZE = 49

## Функция для заполнения матрицы

In [64]:
def initA(n: int, calc_a, calc_b, calc_c, calc_p):
  A = np.zeros((n + 1, n + 1))

  # Прописываем первую строчку
  A[0][0] = calc_b(0)
  A[0][1] = calc_c(0)

  # Идем по диагонали
  for i in range(1, n):
    A[i][i-1] = calc_a(i)
    A[i][i]   = calc_b(i)
    A[i][i+1] = calc_c(i)

  # Идем по последней строчке:
  for i in range(n + 1):
    A[-1][i] = calc_p(i)

  return A


array([[5., 1., 0., ..., 0., 0., 0.],
       [1., 5., 1., ..., 0., 0., 0.],
       [0., 1., 5., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 5., 1., 0.],
       [0., 0., 0., ..., 1., 5., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [71]:
ret_one = lambda i: 1
A = initA(SIZE, ret_one, lambda i: 5, ret_one, ret_one) # Матрица системы
f = np.transpose([np.arange(1, SIZE + 2)]) # Вектор правых частей

expandedA = np.concatenate((A, f), axis=1) # Получаем расширенную матрицу системы

print(A)
print('')
print(np.transpose(f))
print('')
print(expandedA)

[[5. 1. 0. ... 0. 0. 0.]
 [1. 5. 1. ... 0. 0. 0.]
 [0. 1. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 5. 1. 0.]
 [0. 0. 0. ... 1. 5. 1.]
 [1. 1. 1. ... 1. 1. 1.]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50]]

[[ 5.  1.  0. ...  0.  0.  1.]
 [ 1.  5.  1. ...  0.  0.  2.]
 [ 0.  1.  5. ...  0.  0.  3.]
 ...
 [ 0.  0.  0. ...  1.  0. 48.]
 [ 0.  0.  0. ...  5.  1. 49.]
 [ 1.  1.  1. ...  1.  1. 50.]]


## Определяем методы для прямого метода Гаусса

In [72]:
def mainElemIdx(mx, idx):
  main_elem = mx[idx][idx]
  main_idx = idx

  for i in range(idx, len(mx)):
    if (mx[i][idx] > main_elem):
      main_elem = mx[i][idx]
      main_idx = i
  
  return main_idx

def forwardGauss(mx):
  rowNum = len(mx)
  iterEnd = min(rowNum, len(mx[0]))

  for i in range(iterEnd):
    mainIdx = mainElemIdx(mx, i) # Найти главный элемент
    mx[[mainIdx, i]] = mx[[mainIdx, i]] # Поменять строки матрицы
    for j in range(i + 1, rowNum):
      mx[j] -= mx[j][i] / mx[i][i] * mx[i] # Вычесть строку с главным элементом

  return mx

def backwardGauss(mx):
  rowNum = mx.shape[0]
  colNum = mx.shape[1]

  assert rowNum <= colNum

  ans = np.zeros((colNum - 1, 1))
  for i in range(rowNum - 1, -1, -1):
    sum = 0
    for j in range(i + 1, colNum - 1):
      sum += mx[i][j] * ans[j][0]
    ans[i][0] = (mx[i][rowNum] - sum) / mx[i][i]

  return ans


## Получаем невязку для метода Гаусса

In [73]:
ans = backwardGauss(forwardGauss(expandedA)) # Получаем ответ
diff = f - np.matmul(A, ans) # Вектор с ошибками

norm = sum(abs(diff)) # Вычисляем невязку по второй норме
print(norm)


[5.32907052e-14]
